###
GET http://localhost:8080/api/users

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "{{email}}",
  "firstName": "{{firstName}}",
  "lastName": "{{lastName}}",
  "birthDate": "{{birthDate}}"
}

###
GET http://localhost:8080/api/users/{{email}}

###
GET http://localhost:8080/api/notes?potentialUserId={{email}}

###
DELETE http://localhost:8080/api/users/{{email}}

###
GET http://localhost:3000/api/notes

###
GET http://localhost:3000/api/notes/{{email}}
